require("symbols-outline").setup({
  wrap = true,
  position = 'left',
  relative_width = false,
  width = 30,

  keymaps = {
    close = {},
    goto_location = "<Cr>",
    focus_location = "<Tab>",
    hover_symbol = "<C-space>",
    toggle_preview = "K",
    rename_symbol = "<F6>",
    code_actions = {},
    fold = "h",
    unfold = "l",
    fold_all = "M",
    unfold_all = "R",
    fold_reset = {},
  },
  symbols = {
    File = { icon = "", hl = "@text.uri" },
    Module = { icon = "", hl = "@namespace" },
    Namespace = { icon = "󰙅 ", hl = "@namespace" },
    Package = { icon = "󰜬", hl = "@namespace" },
    Class = { icon = "𝓒", hl = "@type" },
    Method = { icon = "󰊕", hl = "@method" },
    Property = { icon = "", hl = "@method" },
    Field = { icon = "", hl = "@field" },
    Constructor = { icon = "", hl = "@constructor" },
    Enum = { icon = "", hl = "@type" },
    Interface = { icon = " ", hl = "@type" },
    Function = { icon = "󰊕", hl = "@function" },
    Variable = { icon = "", hl = "@constant" },
    Constant = { icon = "", hl = "@constant" },
    String = { icon = '󱀍', hl = "@string" },
    Number = { icon = "", hl = "@number" },
    Boolean = { icon = "󰨙", hl = "@boolean" },
    Array = { icon = "", hl = "@type" },
    Object = { icon = "", hl = "@type" },
    Key = { icon = "", hl = "@type" },
    Null = { icon = "NULL", hl = "@type" },
    EnumMember = { icon = "", hl = "@field" },
    Struct = { icon = "", hl = "@type" },
    Event = { icon = "🗲", hl = "@type" },
    Operator = { icon = "+", hl = "@operator" },
    TypeParameter = { icon = "𝙏", hl = "@parameter" },
    Component = { icon = "", hl = "@function" },
    Fragment = { icon = "", hl = "@constant" },
  },
})
