keys:
  # Users
  - &users:
    - &vaw 508F0546A3908E3FE6732B8F9BEFF32F6EF32DA8
  # Hosts
  - &hosts:
    - &hades age1p6ju0gfsmdd4l7u47rxnmqz6q4jsm480kf2r05dy2f666sflr5lqh770u2
    - &zeus age1jgzl7nr0n67yh2gar2arkc47h8weus8xrd2ckd0wm0q27dtpxyyqj3ezn5

creation_rules:
  - path_regex: features/desktop/secrets.yaml$
    key_groups:
    - age:
      - *hades
      - *zeus
      pgp:
      - *vaw
