keys:
  # Users
  - &users:
    - &vawvaw 508F0546A3908E3FE6732B8F9BEFF32F6EF32DA8
  # Hosts
  - &hosts:
    - &vaw-pc age1c98lnjkgjfen7ld8u5a846vklqxzhw80srk3l8292kaf333c4egqtfl6gc
    - &vaw-pi age15nl6rrcuswt8xynh562agcvf3jjcf4e0ud5rzqp6f6cns0vayvjqjc00lt

creation_rules:
  - path_regex: common/secrets.yaml$
    key_groups:
    - age:
      - *vaw-pc
      - *vaw-pi
      pgp:
      - *vawvaw
  - path_regex: common/optional/containers/.+/.*secret.*
    key_groups:
    - age:
      - *vaw-pi
      # for testing
      - *vaw-pc
      pgp:
      - *vawvaw
