keys:
  # Users
  - &users:
    - &vawvaw 508F0546A3908E3FE6732B8F9BEFF32F6EF32DA8
  # Hosts
  - &hosts:
    - &vaw-pc age1p6ju0gfsmdd4l7u47rxnmqz6q4jsm480kf2r05dy2f666sflr5lqh770u2
    - &vaw-laptop age127ntjlxgeprk2a3zjvlzem3en9pmn98kkj0mesqzvque8jwzxa8srkggnx
    - &vserver age1utm6tep8fwcgcvkwsmdsmz67jvtmp4j2yrae2ndxnhywaks80daq2xgts5

creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *vaw-pc
      - *vaw-laptop
      pgp:
      - *vawvaw
