{
  imports = [
    ./ntfy
    ./nvim
    ./alacritty.nix
    ./audio.nix
    ./bemenu.nix
    ./direnv.nix
    ./discord.nix
    ./dunst.nix
    ./firefox.nix
    ./font.nix
    ./gpg.nix
    ./keepassxc.nix
    ./mail.nix
    ./obsidian.nix
    ./signal-desktop.nix
    ./spotify.nix
    ./syncthing.nix
    ./theme.nix
    ./tor-browser.nix
    ./xdg.nix
    ./xkb.nix
  ];
}
