borg-andorra: ENC[AES256_GCM,data:/N8U5ZT6n1FPdyZW7ojKiFsB3NsSzMFsln/bVfv/Z6MF6T4aJyeWIsY3q7DELIV3OQqO6rCrMTemOaiq16KUm1z0gCIF5B+vWxU48Rytd88UbInY7kuV+1iSVlP7qswxOYbfLUbwWDUWXPIyJYT4es3J7N8YNKwrAKNwSIO/6j4=,iv:RECnX3bUJFOMP5w69+8wDLYLXmunnoijnDaihHimaM0=,tag:uwGlIoE1LKStN2sUIG/pPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dr06wca7tc3yfp8qs3ha8pgl46p9rm3zukc2y626kd9a5ughtc3qt598fj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLVGI1VERIVlYvTmxybDRo
            Z3JsVXlPY0NzSG42T2V5TS9kSW5wdzQ4alc0ClR3dnlCOTlYeTF4SXR0UFgvcWtC
            Qyt3ZllIN25mM1N3UGs2bThYV1lYWFEKLS0tIGNtaEp6Zm5Lck51Znk2cXZUemov
            SGtZaytlUldRakVDU3EwaWlXL3BEbXcKEV93HRmCRlLJdvkUZBKRA0QV+xjJ7OLm
            IxmVFNlUPglRrMIYdiGtZ02sXdEO3qjcqJ1Lpx7xN5FyWaIAlxOzQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-01T07:22:49Z"
    mac: ENC[AES256_GCM,data:j2T1P7yuM72j3Mvy5vncHp0v55VkZ6GrDu8Z4+SdCDdfnvC2pXfou42q6LBugDK5OMbNdG1uAxWFZB4c2HqEBymQp1Wi//gX50Empa2sGt/eYfRJVHjPfhJ1Hw/x6qCNNwBYXnqdkh/2rvlwXqIWeDjDyaWu/YwWLo5wSmrRaJ0=,iv:PIoakyi0gAKTVndlHc/oGXCncC4pBnY/f272uWZBvjo=,tag:8Y0/Yus+mNdF+cxSYa64Yw==,type:str]
    pgp:
        - created_at: "2023-11-01T07:21:21Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwAAAAAAAAAAAQ/9Hh9rNaEEqCleCY83oBTmpdTrZGej19d3I+SrI8IWdj+H
            rYp3BEhO7+k9Cu71tyRj0+zdJXYZK+evOa8n0VJqdl2gIcnSJksDouZNYLG97c3Q
            sDDOwnEiyuYcrrwn2R1LZZAfuzvy4TzVWIO0RyKWPAaRFJNIr/oYA8eVYb1bFaQB
            CRTGKthkUR1OtMEatsjkxJq4CVHGB2+YgMw3CLkVPDckQ6TQgFm74johWO3NoKOQ
            XRFQVTs1ftW83USRIH3PJ+2OtsvAsk3INSwgkYC/dcMGEeW84mp6eW91d5jrv2ZC
            rv8of4m8MlB6Q0yUZDh61uxxSSofwbYlGvgFQg6IautFN4gH6kHYCUJvJVMq/NpO
            h/mjKmbvoxj9sjR8js8TGmxfaJJtO2RDN61abLqC452QeOkWNKu3aXYuE25nzbJS
            XhDuGPORETTyQDCJYKo4zb4UTQ865Nhd+70n2mIXlPRXpqtcOPEzvxeF7xTklaQF
            7K6RxRM+LR1N1Ybw6U0fGAjfe3Xr3+x5hdBMMRS67DEePoYXp3xjNqfs7koqv7Bo
            ssbOk4+ajm7zxaH8AkLkRTdQhpPtCuKOg7rHVkRp2napcFT/cFJ5OJF/te8ezTCm
            rRwbB7cFwCQhaujSAmC6MlwmawjgMDnvTnM6Szj0XpwX7hEg3pY+MhCRjZO4QX3S
            XgG2aSy0BgTB1LbAIRM/k/IsYdHd2phbtBhg9eROfiAd59ND635OVqqWI36nosf2
            Ehg20KWHA48OQdgCkgRfNMQka1zdmMHkQeDZgVPLNip+EvMsSmnUu8rs8dv9i5E=
            =h1SW
            -----END PGP MESSAGE-----
          fp: 508F0546A3908E3FE6732B8F9BEFF32F6EF32DA8
    unencrypted_suffix: _unencrypted
    version: 3.8.1
