borg-andorra: ENC[AES256_GCM,data:/N8U5ZT6n1FPdyZW7ojKiFsB3NsSzMFsln/bVfv/Z6MF6T4aJyeWIsY3q7DELIV3OQqO6rCrMTemOaiq16KUm1z0gCIF5B+vWxU48Rytd88UbInY7kuV+1iSVlP7qswxOYbfLUbwWDUWXPIyJYT4es3J7N8YNKwrAKNwSIO/6j4=,iv:RECnX3bUJFOMP5w69+8wDLYLXmunnoijnDaihHimaM0=,tag:uwGlIoE1LKStN2sUIG/pPQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wa8vc5kql0230k2qfv6fvlcnwnhqme4wv25r7sac6q6pd9flw38sde7d3h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDS3UxaVYvMWRQOXlzejZN
            Q1VwNy84cDAvZ3FXRHlVem14NWhucjBueUdJCks1TkNMeDgwdE5JaXg5aE85OWxu
            VTYvTy9FNTNVbmxLdWE2QWZDRmRPVWcKLS0tIC9RcGJFRWQ5MDdlRkFaTGdFVWtl
            ejlkcG41NjVndXBwb1JQZXV6ZU1rZjgKV4oI8Bv9ROwdh62a+k2+OL6SSgcESqBV
            eztMyBGLQ28uJFQ7mzW9KIJaD4GfYGvPgHpITTwGXyQ+rf5RFpLpVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-01T07:22:49Z"
    mac: ENC[AES256_GCM,data:j2T1P7yuM72j3Mvy5vncHp0v55VkZ6GrDu8Z4+SdCDdfnvC2pXfou42q6LBugDK5OMbNdG1uAxWFZB4c2HqEBymQp1Wi//gX50Empa2sGt/eYfRJVHjPfhJ1Hw/x6qCNNwBYXnqdkh/2rvlwXqIWeDjDyaWu/YwWLo5wSmrRaJ0=,iv:PIoakyi0gAKTVndlHc/oGXCncC4pBnY/f272uWZBvjo=,tag:8Y0/Yus+mNdF+cxSYa64Yw==,type:str]
    pgp:
        - created_at: "2024-03-18T13:16:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwAAAAAAAAAAAQ//bmYW4/Q5XjjQxMYSwMn9hg8nEbdv67jMuTW5DWWuBEle
            w08EGm3ZadHs11Z8DGN6GLnCzaRg7K9p9INjlBMd3VMzd2BNTFzsDSn8B86WixRt
            kE0stlqoNg6FvNYxru6ZIUPNTC48xrYdZPku0dyCDBGNXeXNma1fYjZwNI29daZR
            mAk2MtX0mYb29RrgIoeEzkyKxmWWEzwjwKHRZNFbftVG4OR1spHuGsQg/SvmYCWK
            FbwNoQVOiTV6dnlkWdjrF4gx6VdBN+MUem5ETt20PZKXU5+3nxWKvqx2QzvmL3+9
            x4LhAtgczTaHit9e23oJGBaEhWBSCvx5VqfWo+Okb3f0wJMyFQSyvhe6uqXoR4n1
            un6RclvLB1izcXXvwYAEueEf0Lj+BL2Q+tVPw+5SzOUwT9ajw5hZha1hN0kSuQ64
            OKYv1PqWgrSMcM7A3XUdOLzg0S+pMfaolCloZOl9K/EsRUl1b4HP2+IYM7Bq8dt7
            aCm03SdvmL3n2g4JMFHCa5fYkLl/CPTnBNFyYLtd86k6Bh4cg1qUiJe98SvEfIH3
            pGtb649xjo75LAYgCHHPCHz1Rcns/rK7V/5hJKqnMhvnKa5xStydqfJcKV9V4cE8
            ZnB1A2ynu2TguG2qcAhzC7hNh0JxUxEV5OsUEDtFRYUfZBS8djMgjWfqw3JoodLS
            XgGleeDIp2D/t/NZnW7xds7KHqIvD9vCggVdAt5PP26Y2p9UckIn7PP4GkjieBDa
            q+0VuzhxMObpLvC7J8DzuXp1ehoMWzAgxfV4SK9XK24MkbB02acCFbTNxLdpsEY=
            =aMcx
            -----END PGP MESSAGE-----
          fp: 508F0546A3908E3FE6732B8F9BEFF32F6EF32DA8
    unencrypted_suffix: _unencrypted
    version: 3.8.1
