keys:
  # Users
  - &users:
    - &vaw 508F0546A3908E3FE6732B8F9BEFF32F6EF32DA8
  # Hosts
  - &hosts:
    - &hades age1c98lnjkgjfen7ld8u5a846vklqxzhw80srk3l8292kaf333c4egqtfl6gc
    - &zeus age13qscya8p0ckmxw9aq2uyrlsfgurrj97a5wplkczluaqcur4gxc2qq9spcr
    - &athena age1dr06wca7tc3yfp8qs3ha8pgl46p9rm3zukc2y626kd9a5ughtc3qt598fj
    - &artemis age1wa8vc5kql0230k2qfv6fvlcnwnhqme4wv25r7sac6q6pd9flw38sde7d3h
    - &nyx age1phxj8e7z7tpr2pw9dnkx2xgeq5zpw4v33m5rur7hgzun0m90s48qycgyed
  # Homes
  - &homes:
    - &hades-vaw age1p6ju0gfsmdd4l7u47rxnmqz6q4jsm480kf2r05dy2f666sflr5lqh770u2
    - &zeus-vaw age1jgzl7nr0n67yh2gar2arkc47h8weus8xrd2ckd0wm0q27dtpxyyqj3ezn5

creation_rules:
  - path_regex: desktop.yaml$
    key_groups:
    - pgp:
      - *vaw
      age:
      - *hades-vaw
      - *zeus-vaw
  - path_regex: mail.yaml$
    key_groups:
    - pgp:
      - *vaw
      age:
      - *artemis
      - *hades-vaw
      - *zeus-vaw
  - path_regex: system.yaml$
    key_groups:
    - pgp:
      - *vaw
      age:
      - *hades
      - *zeus
      - *athena
      - *artemis
      - *nyx
  - path_regex: artemis.yaml$
    key_groups:
    - pgp:
      - *vaw
      age:
      - *artemis
  - path_regex: artemis-nyx-borg$
    key_groups:
    - pgp:
      - *vaw
      age:
      - *artemis
